DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS item_requests CASCADE;


CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255),
    email   VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS item_requests
(
    item_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description     VARCHAR(255),
    requestor_id    BIGINT REFERENCES users (user_id),
    created         TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS items
(
    item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(255),
    owner_id    BIGINT,
    available   BOOLEAN,
    item_request_id  BIGINT REFERENCES item_requests (item_request_id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    item_id    BIGINT REFERENCES items (item_id),
    booker_id  BIGINT,
    status     VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id      BIGINT REFERENCES items (item_id),
    author_id    BIGINT REFERENCES users (user_id),
    text         VARCHAR(255),
    created_date TIMESTAMP WITHOUT TIME ZONE
);

